# Generated by Django 4.1.4 on 2022-12-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
