# Generated by Django 4.1.4 on 2022-12-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0013_rename_description_course_description_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='first_name_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='last_name_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
