# Generated by Django 4.1.4 on 2022-12-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0016_ability_userform_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='user_form.ability'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='languages',
            field=models.ManyToManyField(blank=True, to='user_form.language'),
        ),
    ]
