# Generated by Django 4.1.4 on 2022-12-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0017_alter_userform_abilities_alter_userform_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='language',
            name='level',
        ),
        migrations.AddField(
            model_name='language',
            name='levels',
            field=models.ManyToManyField(blank=True, to='user_form.languagelevel'),
        ),
    ]
