# Generated by Django 4.1.4 on 2022-12-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0018_languagelevel_remove_language_level_language_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ability',
            name='level',
        ),
        migrations.AddField(
            model_name='ability',
            name='levels',
            field=models.ManyToManyField(to='user_form.abilitylevel'),
        ),
    ]
